[params]
  env = "production"
  title = "Keyboard Heaven"
  description = "Your path to keyboard heaven"
  
  [params.homeInfoParams]
    Title = "Your path to keyboard heaven"
    Content = "Tips, layouts and optimization techniques to make typing feel comfortable and effortless."